### ISSUE TITLE
null

### ISSUE THREAD

**Issue by PatrykPospiech** [hubertgad/Repeat#12]
https://github.com/hubertgad/Repeat/blob/0a89aa3fb0b60434787e65d469eae1115d3671d4/Repeat.DataAccess/Services/QuestionService.cs#L26

nie rozumiem zabardzo zamyslu stosowania '?' i domyslnego przypisywania nulla

**Comment by hubertgad** [comment]
> nie rozumiem zabardzo zamyslu stosowania '?' i domyslnego przypisywania nulla

Z tej funkcji program korzysta w kilku miejscach, i nie zawsze filtrujemy po kategorii albo zestawie. Mógłbym zwrócić listę pytań i wykonać filtrowanie zwróconego rezultatu w kontrolerze konkretnej strony, ale czy to nie obniżyłoby wydajności całej aplikacji? Chciałem tutaj uniknąć pobieranie z bazy niepotrzebnych rekordów. Alternatywnie mógłbym stworzyć cztery różne funkcje.

**Comment by hubertgad** [comment]
Już tak nie ma :D
