### ISSUE TITLE
foreach

### ISSUE THREAD

**Issue by PatrykPospiech** [hubertgad/Repeat#15]
https://github.com/hubertgad/Repeat/blob/0a89aa3fb0b60434787e65d469eae1115d3671d4/Repeat.DataAccess/Services/QuestionService.cs#L64

tak btw foreach tez mozna wywolywac parallel

**Comment by hubertgad** [comment]
Wiem, jest na samym początku zielonej książki, ale boję się tak robić 😂 spróbuję zmienić i zobaczę co się stanie

**Comment by PatrykPospiech** [comment]
i jak tam ? tak samo nizej masz linq ktory mozna zamineic na plinq ale przetestuj to dobrze bo zla implementacja moze zdupic sprawe

**Comment by hubertgad** [comment]
Zrobiłem Parallel.ForEach, tak jak napisano na pierwszych stronach mądrej książki, spodziewałem się, że rezultaty nie będą w takiej samej kolejności, ale nie zauważyłem żadnej różnicy. Co do tych LINQ to który masz na myśli? Bo ja nie wiem czy bym w nich coś jeszcze zmieniał (mam wszystkie asynchronicznie wykonywane, musiałbym poczytać jaką to różnice by zrobiło).

**Comment by PatrykPospiech** [comment]
nie pamietam gdzie to bylo i teraz nie wiedze :D
