### ISSUE TITLE
logika zaczyna przenikac sie z kontrolerami

### ISSUE THREAD

**Issue by PatrykPospiech** [hubertgad/Repeat#16]
https://github.com/hubertgad/Repeat/blob/0a89aa3fb0b60434787e65d469eae1115d3671d4/Repeat.DataAccess/Services/QuestionService.cs#L11

mam wrazenie ze robi sie tu za duzo logiki, staje sie to powoli nieczytelne. wyeksportowalbym wiekszosc do innej klasy, helperow, extensionow zeby poszukac jak najwiecej wspolnych elementow a kontroler serwisu ograniczyc do minimum.

**Comment by hubertgad** [comment]
Dokonałem małej refaktoryzacji kodu i zmniejszyłem o połowę objętość tej klasy, m. in. dzięki zastosowaniu szablonów i podzieleniu zapytań na mniejsze kawałki w funkcjach, które przyjmują opcjonalne parametry. Wydaje mi się, że jest trochę bardziej przejrzyście teraz. 

**Ogólnie założenie jest takie, że tutaj jest cała logika związana z DB, a w "kontrolerze" flow programu.** 

Mógłbym teoretycznie zrobić tutaj małe dziedziczonko, żeby się to rozgałęziło mi na QuestionService, TestService, itd... Czy robić te extensiony?

**Comment by PatrykPospiech** [comment]
`Ogólnie założenie jest takie, że tutaj jest cała logika związana z DB, a w "kontrolerze" flow programu.`
spoko moze byc.

co do extensionow jezeli nie ma takiej potrzeby to ich nie robimy bo sa one wygodne ale nie sa najlepsza praktyka w wielu wypadkach ( glownie chodiz o testowalnosc kodu )
